project:
  type: website
  output-dir: docs

website:
  description: "Machine learning articles, notebooks, and papers"
  site-url: https://zzfb.github.io # you must change this appropriately for RSS feeds to work properly
  title: "Zhong's ML Notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/zhong-zhang-59b63a23/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    math: mathjax
    toc: true
    code-fold: show
    anchor-sections: true



